[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "/matur"
    to = "/blog/maturitni-temata-purkynka/"
    status = 301
    force = false
